language: generic 

# telling Travis to have super user permissions to execute this build
sudo: required

# Travis to know that we need docker CLI for install
services:
    - docker

# steps/commands to execute before testing/deploy
before_install:
    # -t tagging with user name & github project
    -  docker build -t rupaklama/docker-react-app -f Dockerfile.dev .

# this command to run test
script:
    - docker run -e CI=true rupaklama/docker-react-app npm run test
